name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
          mkdir build
          cd build
          cmake ..
          make -j4
    - name: Run test
    - run: ./bin/testcpp
